### ISSUE TITLE
Last ionic and --prod : white screen

### ISSUE THREAD

**Issue by tgensol** [zyra/ionic2-super-tabs#174] opened 2017-10-02 12:26 UTC
Hi there,

I wanted to use the super tabs, it is working well when I am --dev and on simulator, but once it is deployed with --prod (through TestFlight or Play store), the super tabs is not working and I only got a white screen without any error... I do not understand  what is happening. I tried to update the package.json and the tsconfig.json to match the last ionic, but it not working either...

`

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v6.11.3
    npm        : 5.3.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy
`

Thanking you in advance,
Regards

**Comment by tgensol** [comment] 2017-10-02 13:05
With the chrome://inspect I saw this  : 

<img width="414" alt="capture d ecran 2017-10-02 a 15 04 49" src="https://user-images.githubusercontent.com/7864896/31078626-2b7411ae-a783-11e7-8db0-69e187e89048.png">


Hope this can help

**Comment by tgensol** [comment] 2017-10-02 13:37
I finally found that the css of the super-tabs was not inserted in my app with the --prod flag... any idea ?

**Comment by aleygues** [comment] 2017-10-02 14:18
Same here

**Comment by tgensol** [comment] 2017-10-02 14:22
@aleygues Just add the super-tabs.scss, in your app.scss or something and it will work.

**Comment by aleygues** [comment] 2017-10-02 15:30
@tgensol Oh yeah clever. It's working fine now. Thanks !

**Comment by karansharma27** [comment] 2017-10-06 05:33
Its a problem with the latest ionic-angular version, i.e 3.7.1

**Comment by C0reTex** [comment] 2017-10-06 13:43
Instead of copying `.scss` files into one another you can also compile your project with `ionic cordova run *platform-name* --aot --minifyjs --minifycss --optimizejs`. This fixed the issue for me.

**Comment by akhatri** [comment] 2017-10-07 04:03
i am using buddybuild for my projects and they use the `--prod` flag for release builds. I've tried to include the .`scss` but the 2nd tab on my homepage shows a white screen (it seems that the page has not been loaded inside the DOM container). It loads completely fine without the prod flag. Im on the latest versions of ionic and supertabs

**Comment by akhatri** [comment] 2017-10-10 01:42
I have narrowed down the problem and it has something to do with the chartist module plugin. I have asked for help on the project repo. FYI https://github.com/willsoto/ng-chartist/issues/150 incase anyone is in the same situation as me.

**Comment by JaneDawson** [comment] 2017-10-16 07:45
> Instead of copying .scss files into one another you can also compile your project with ionic cordova run *platform-name* --aot --minifyjs --minifycss --optimizejs. This fixed the issue for me.

@C0reTex: Thanks for the hint. Does `--aot --minifyjs --minifycss --optimizejs` include everything that `--prod` does? What is the difference?

Copying the `super-tabs.scss` in `app.scss` seems to work for some time, but after running in background for some time, the tab-bar is not shown anymore at all...

**Comment by DevJuliocesar** [comment] 2017-10-18 17:39
I belive the problem is the version of super-tabs, because, a while ago the plugin worked

**Comment by C0reTex** [comment] 2017-10-19 14:13
@JaneDawson I browsed through the ionic source code on GitHub and it seems that it does the same optimization as `--prod`. However, as stated in the [Ionic App-Script documentation](https://github.com/ionic-team/ionic-app-scripts#ionic-environment-variables) the `process.env.IONIC_ENV` is probably not set to **prod**. By default this env is set to **dev**.
But I can't tell if this affects the build application in any way.

**Comment by rashnk** [comment] 2017-10-23 17:27
any update on this? @ihadeed. its showing white blank only

**Comment by leonardosalles** [comment] 2017-10-25 19:29
same here

**Comment by stionic** [comment] 2017-10-29 11:02
Hi, I also got the same error and fix it by add this line to variables.scss:

@import "../../ionic2-super-tabs/dist/components/super-tabs";

Good luck 😃

**Comment by DevJuliocesar** [comment] 2017-10-30 16:49
@stionic very thank you!!

**Comment by rashnk** [comment] 2017-11-05 06:22
@stionic , worked thanks,, but the author still dint find the solution

**Comment by ihadeed** [comment] 2018-01-26 07:14
Closing in favour of #254  .. update to latest version & post any issues you're having on that thread.

**Closed by ihadeed** 2018-01-26 07:14 UTC
