### ISSUE TITLE
[Version 4.1.5]: all super-tab components collapsed to 0, no content, smaller icons

### ISSUE THREAD

**Issue by Unkn0wn0x** [zyra/ionic2-super-tabs#217] opened 2017-11-11 16:18 UTC
After upgrading from version `4.1.4` to `4.1.5` I figured out, that something doesn't work properly. I think it's related to this commit: https://github.com/zyra/ionic2-super-tabs/pull/204/commits/f00f40a2888bfbf1e2233927dfced8913723a5f5

The behaviour with version `4.1.5` is that the content inside the super-tab components are all collapsed to 0. So there is no visible content inside the tabbed page. Also the icons are downsized. I think here is some resizing missing.

![v4 1 5](https://user-images.githubusercontent.com/31123135/32691200-09a0c7ca-c704-11e7-882c-db67c441e26a.png)

---

The behaviour with version `4.1.4` is as expected, everything works fine in my case. The white card on the bottom of the screenshot is my content.

![v4 1 4](https://user-images.githubusercontent.com/31123135/32691197-ff5b2f1c-c703-11e7-9935-06bb3e85a822.png)

**Comment by icsvortex666** [comment] 2017-11-11 16:53
Yeah, also error #193 is still present

**Comment by mugavri** [comment] 2017-11-12 14:49
it also for me

**Comment by beqaweb** [comment] 2017-11-13 08:14
Same problem here

**Comment by aleksvidak** [comment] 2017-11-13 08:30
If someone succeded to apply some quick fix, it would be great :-) I have this issue on iOS only, android works for me.

**Comment by beqaweb** [comment] 2017-11-13 08:33
Well, it doesn't work for Ionic **v4.1.5**

**Comment by zjcboy** [comment] 2017-11-13 09:59
it also for me

**Comment by Unkn0wn0x** [comment] 2017-11-13 11:33
@aleksvidak The quick fix would be to revert the changes, which were made in https://github.com/zyra/ionic2-super-tabs/commit/f00f40a2888bfbf1e2233927dfced8913723a5f5#diff-2c687355ad1a65d5095f46fdde86e8a9 or just use v4.1.4.

**Comment by aleksvidak** [comment] 2017-11-13 11:50
@beqaweb @Unkn0wn0x thanks guys, I installed v4.1.4, it works for me. Cheers

**Comment by SteveKennedy** [comment] 2017-11-15 01:47
Reverting to 4.1.4 worked.   But 4.1.5 is definitely the problem.  I bounced back and forth between the versions just to be sure.  I only have Android.

**Comment by Topiya** [comment] 2017-11-17 07:16
I am also facing the same issue

**Comment by yanxiaodi** [comment] 2017-11-19 06:56
I have the same problem.

**Comment by ashley-s** [comment] 2017-11-22 07:29
same here

**Comment by Bandcy** [comment] 2017-11-24 00:59
same here. reverted back to 4.1.4
npm install ionic2-super-tabs@4.1.4

**Comment by allanpoppe** [comment] 2017-11-24 22:28
This is happening because of a missing .scss.
See #218 .

**Comment by sagie212** [comment] 2017-12-12 15:45
any news?

**Comment by SteveKennedy** [comment] 2017-12-19 22:20
@ihadeed Can you point me in right direction? I tried to figure out what was going on, but haven't figured this out.  I would be glad to contribute the code changes, but can't determine the _why_ this is happening? Any help or guidance would be appreciated.

**Comment by ihadeed** [comment] 2017-12-19 23:25
@SteveKennedy 
It's hard to guess what the problem here is. Can you quickly provide me with the setup that you have so I can reproduce the issue? 

The last time I tried the example project, it was working fine. I remember there was an issue with a specific version of `@ionic/app-scripts` that wasn't copying SCSS from external modules. This issue was fixed in the next release.

**Comment by SteveKennedy** [comment] 2017-12-21 15:06
Thank you @ihadeed 

1. Using latest version of Ionic, create a brand new Ionic app (_ionic new myapp_).  Ensure you select TABS template. This will also do a basic _npm install_.

2. Install super tabs 4.1.5: _npm install --save ionic2-super-tabs_

3. Add _SuperTabsModule.forRoot()_ into main module’s Import node. You’ll also need to: _import { SuperTabsModule } from 'ionic2-super-tabs’;_

4. Open src/pages/tabs/tabs.html and replace contents with:
```
<super-tabs>
  <super-tab [root]="tab1Root" title="First page" icon="home"></super-tab>
  <super-tab [root]="tab2Root" title="Second page" icon="pin"></super-tab>
  <super-tab [root]="tab3Root" title="Third page" icon="heart"></super-tab>
</super-tabs>
```

5. Run Ionic serve. Notice how weird it looks.

**Comment by gvhuyssteen** [comment] 2018-01-16 20:27
I added a temporary solution for now in the comments of my PR #248.
This will allow you to save the solution to GitHub as part of your repository.

**Comment by ihadeed** [comment] 2018-01-25 05:29
Will be fixed in the next release, tonight.

**Closed by ihadeed** 2018-01-25 05:29 UTC
