### ISSUE TITLE
Does not support ionic3.5？

### ISSUE THREAD

**Issue by kongdewen1994** [zyra/ionic2-super-tabs#96] opened 2017-07-01 04:17 UTC
Uncaught (in promise): TypeError: this.linker.initNav is not a function
TypeError: this.linker.initNav is not a function
    at SuperTabs.webpackJsonp.292.SuperTabs.ngAfterViewInit (http://localhost:8100/build/0.main.js:252:39)
    at callProviderLifecycles (http://localhost:8100/build/main.js:11521:18)
    at callElementProvidersLifecycles (http://localhost:8100/build/main.js:11496:13)
    at callLifecycleHooksChildrenFirst (http://localhost:8100/build/main.js:11480:17)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12512:5)
    at callViewAction (http://localhost:8100/build/main.js:12867:21)
    at execComponentViewsAction (http://localhost:8100/build/main.js:12799:13)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12510:5)
    at callWithDebugContext (http://localhost:8100/build/main.js:13566:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (http://localhost:8100/build/main.js:13106:12)

**Comment by Rainyer** [comment] 2017-07-01 05:01
I am trying to implement super tabs on Ionic 3.5 project too, but I got the same error.

**Comment by ihadeed** [comment] 2017-07-02 02:18
Duplicate of #94

**Closed by ihadeed** 2017-07-02 02:18 UTC
