### ISSUE TITLE
this.linker.initNav is not a function

### ISSUE THREAD

**Issue by Lesther993** [zyra/ionic2-super-tabs#98] opened 2017-07-02 04:57 UTC
I have this error:
Uncaught (in promise): TypeError: this.linker.initNav is not a function
TypeError: this.linker.initNav is not a function
    at SuperTabs.ngAfterViewInit

Im using :
node 6.11.0,  
npm 3.10.10

    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.5.0",
    "ionic2-super-tabs": "^2.6.3",
    "ionicons": "3.0.0",
    "latest": "^0.2.0",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"

**Comment by ihadeed** [comment] 2017-07-02 04:58
Duplicate of #94 

This is fixed in master, I'll publish a release soon.

**Closed by ihadeed** 2017-07-02 04:58 UTC
